{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Failure"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ioginfrastructure\/iogretrymanager\/disposition\/failure"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/IoGInfrastructure\/documentation\/IoGInfrastructure\/IoGRetryManager\/Disposition\/Failure","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The retry attempt failed"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Failure"}],"title":"IoGRetryManager.Disposition.Failure","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:17IoGInfrastructure0A13GRetryManagerC11DispositionO7FailureyA2EmF","modules":[{"name":"IoGInfrastructure"}]},"hierarchy":{"paths":[["doc:\/\/IoGInfrastructure\/documentation\/IoGInfrastructure","doc:\/\/IoGInfrastructure\/documentation\/IoGInfrastructure\/IoGRetryManager","doc:\/\/IoGInfrastructure\/documentation\/IoGInfrastructure\/IoGRetryManager\/Disposition"]]},"references":{"doc://IoGInfrastructure/documentation/IoGInfrastructure/IoGRetryManager":{"role":"symbol","title":"IoGRetryManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IoGRetryManager"}],"abstract":[{"type":"text","text":"Singleton class that manages attempts to execute sections of code that previously failed to complete"}],"identifier":"doc:\/\/IoGInfrastructure\/documentation\/IoGInfrastructure\/IoGRetryManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IoGRetryManager"}],"url":"\/documentation\/ioginfrastructure\/iogretrymanager"},"doc://IoGInfrastructure/documentation/IoGInfrastructure":{"role":"collection","title":"IoGInfrastructure","abstract":[],"identifier":"doc:\/\/IoGInfrastructure\/documentation\/IoGInfrastructure","kind":"symbol","type":"topic","url":"\/documentation\/ioginfrastructure"},"doc://IoGInfrastructure/documentation/IoGInfrastructure/IoGRetryManager/Disposition":{"role":"symbol","title":"IoGRetryManager.Disposition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Disposition"}],"abstract":[{"type":"text","text":"The result of the retry attempt returned to the Retry Manager from the closure being retried"}],"identifier":"doc:\/\/IoGInfrastructure\/documentation\/IoGInfrastructure\/IoGRetryManager\/Disposition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Disposition"}],"url":"\/documentation\/ioginfrastructure\/iogretrymanager\/disposition"},"doc://IoGInfrastructure/documentation/IoGInfrastructure/IoGRetryManager/Disposition/Failure":{"role":"symbol","title":"IoGRetryManager.Disposition.Failure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Failure"}],"abstract":[{"type":"text","text":"The retry attempt failed"}],"identifier":"doc:\/\/IoGInfrastructure\/documentation\/IoGInfrastructure\/IoGRetryManager\/Disposition\/Failure","kind":"symbol","type":"topic","url":"\/documentation\/ioginfrastructure\/iogretrymanager\/disposition\/failure"}}}